### ISSUE TITLE
total_fee ,  rmb_fee 二选一

### ISSUE THREAD

**Issue by zysoo** [lokielse/omnipay-global-alipay#2]
商品可能以rmb标价， total_fee就不适用。

> “如果商户网站使用人民币进行标价就是用这个参数来替换 total_fee 参数，rmb_fee 和 total_fee 不能同时使用”

所以 total_fee 需要从validate array中去掉，是不是可以额外做validate

**Comment by lokielse** [comment]
刚代码已更正，请重新后尝试。

**Comment by zysoo** [comment]
tested,  looks good.
