### ISSUE TITLE
Requires guzzle6 adapter

### ISSUE THREAD

**Issue by darkphoenixff4** [lokielse/omnipay-global-alipay#21]
Is there any particular reason the guzzle6 adapter is marked as a Composer requirement?  I don't see anything in the code that would absolutely require that adapter, as opposed to any of the other adapters for php-http, and due to version requirements, I'd prefer to use the guzzle5 adapter instead...

**Comment by lokielse** [comment]
@darkphoenixff4 maybe you're right... there is a new release tag.
