### ISSUE TITLE
Only scalar values allowed and sign_type of request_params required

### ISSUE THREAD

**Issue by perdignus** [lokielse/omnipay-global-alipay#4]
Hello, I'm using symfony2 with your package to provide global alipay payments. But I could not successfully implement the last part of the example: the Return/Notify part.
the code that I have now is this:

    public function paymentStatus()
    {
        /**
         * @var Omnipay\GlobalAlipay\WebGateway $gateway
         */
        $gateway = Omnipay::create('GlobalAlipay_Web');
        $gateway->setPartner("overseas_bitest@123.com");
        $gateway->setKey("152bdzec6y9lijsctqx96eaka74272uk");
        $gateway->setEnvironment('sandbox');
        $params = [
            'request_params' => array_merge($_GET, $_POST)
        ];
        $payment = $gateway->completePurchase($params)->send();
        if($payment->isPaid()){
            new Response('success');
        }else{
            new Response('fail');
        }
        return null;
    }    

if I set the request_params to the array_merge, it gives the error:
'Only scalar values are allowed for parameters'
and if I directly send the array_merge it gives:
'The sign_type of request_params is required'

version that I use:
"lokielse/omnipay-global-alipay": "^1.0",

is this a bug in my code? or is this a problem from omnipay?
please help, thank you.

**Comment by lokielse** [comment]
Please provide the follow.
```php
var_dump(array_merge($_GET, $_POST));
exit;
```

**Comment by perdignus** [comment]
array:7 [▼
  "sign" => "ac4ee758012e2e36a332370cbc226f"
  "trade_no" => "20170222100100384020035952"
  "total_fee" => "0.01"
  "sign_type" => "MD5"
  "out_trade_no" => "58d25fc13f930"
  "trade_status" => "TRADE_FINISHED"
  "currency" => "USD"
]

**Comment by lokielse** [comment]
Could you please provide some data of exception(`Only scalar values are allowed for parameters`), such as 
`$e->getFile()`, `$e->getLine()`, `$e->getTraceAsString()`

**Comment by perdignus** [comment]
[stacktrace.txt](https://github.com/lokielse/omnipay-global-alipay/files/899714/stacktrace.txt)
in vendor\omnipay\common\src\Omnipay\Common\Message\AbstractRequest.php at line 174

**Comment by lokielse** [comment]
I think you use the wrong version of `omnipay/common`. 

I find out that `Only scalar values are allowed for parameters` in this commit https://github.com/thephpleague/omnipay-common/pull/81/commits/f7d0131b7feea9c99b4e0d50af1055bc24fb1633 , But not in its `master` branch.

After I update my vendor, my `composer.lock` show `omnipay/common` version is `2.5.2`

**Comment by lokielse** [comment]
The another had same issue with you https://github.com/lokielse/omnipay-alipay/issues/42 , It's a version issue

**Comment by perdignus** [comment]
alright, thanks! I will try to update and will see if that also solves it for me.

**Comment by perdignus** [comment]
sorry for the late reply, but we had issues updating our project. after those were solved we did update to the newest version and now it works. thank you very much for you help
